task_2/quotes/quoteapp/urls.py
from django.urls import path
from . import views
from .apps import QuoteappConfig

app_name = QuoteappConfig.name

urlpatterns = [
    path('', views.main, name='main'),
    path('tag/', views.tag, name='tag'),
    path('author/', views.author, name='author'),
    path('quote/', views.quote, name='quote'),
    path('scraper/', views.start_scraping, name='start_scraping'),
    path('about/<int:author_id>', views.about_author, name='about_author'),
    path('quotes_by_tag/<str:tag_name>', views.quotes_by_tag, name='quotes_by_tag'),

]

task_2/quotes/quotes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quoteapp.urls')),
    path('', include('users.urls')),
]

task_2/quotes/users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

from .views import RegisterView, ResetPasswordView
from .forms import LoginForm

app_name = 'users'

urlpatterns = [
    path('register/',  RegisterView.as_view(), name='register'),
    path('login/',  LoginView.as_view(redirect_authenticated_user=True, template_name='users/login.html',
                                    authentication_form=LoginForm), name='login'),
    path('logout/',  LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('reset-password/', ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

task_2/quotes/quoteapp/models.py
from django.db import models


# Create your models here.


class Tag(models.Model):
    name = models.CharField(max_length=50, null=False, unique=True)

    def __str__(self):
        return f"{self.name}"


class Author(models.Model):
    fullname = models.CharField(max_length=60, null=False)
    born_date = models.DateField(null=False)
    born_location = models.CharField(max_length=100, null=False)
    description = models.CharField(max_length=4500, null=False)

    def __str__(self):
        return f"{self.fullname}"


class Quote(models.Model):
    quote = models.CharField(max_length=2500, null=False)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag)

    def __str__(self):
        return f"{self.quote[0:20]}..."

task_2/quotes/quoteapp/forms.py
from django.forms import ModelForm, CharField, TextInput, DateField, ChoiceField
from django import forms
from .models import Tag, Author, Quote
from datetime import date


class TagForm(ModelForm):
    name = CharField(min_length=3, max_length=25, required=True,
                     widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "Tag"}))

    class Meta:
        model = Tag
        fields = ['name']


class AuthorForm(ModelForm):
    fullname = CharField(min_length=8, max_length=50, required=True,
                         widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "Full name"}))
    born_date = DateField(required=True,
                          widget=forms.SelectDateWidget(years=range(1, date.today().year)))
    born_location = CharField(min_length=5, max_length=50, required=True,
                              widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "Born location"}))
    description = CharField(min_length=10, max_length=5000, required=True,
                            widget=forms.Textarea(attrs={"class": "form-control", "placeholder": "Description"}))

    class Meta:
        model = Author
        fields = ['fullname', 'born_date', 'born_location', 'description']


class QuoteForm(ModelForm):
    quote = CharField(min_length=10, max_length=5000, required=True,
                      widget=forms.Textarea(attrs={"class": "form-control", "placeholder": "Quote"}))
    author = CharField(required=True, widget=forms.Select(attrs={"class": "form-control"}))
    tags = CharField(required=True, widget=forms.Select(attrs={"class": "form-control"}))

    class Meta:
        model = Quote
        fields = ['quote', 'author']
        exclude = ['tags']

task_2/quotes/quoteapp/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, redirect, get_object_or_404

from .forms import TagForm, AuthorForm, QuoteForm
from .models import Tag, Author, Quote
from django.contrib.auth.decorators import login_required
from django.db.models import Count

from . import scraper


# Create your views here.


def main(request):
    quotes = Quote.objects.all()
    paginator = Paginator(quotes, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    tags = Tag.objects.all()
    tag_counts = Tag.objects.annotate(quote_count=Count('quote')).order_by('-quote_count')[:10]
    return render(request, 'quoteapp/index.html', {'page_obj': page_obj, "quotes": quotes, "tag": tags, 'author': author, 'top_tags': tag_counts})


@login_required
def tag(request):
    if request.method == 'POST':
        form = TagForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quoteapp:main')
        else:
            return render(request, 'quoteapp/tag.html', {'form': form})

    return render(request, 'quoteapp/tag.html', {'form': TagForm()})


@login_required
def author(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quoteapp:main')
        else:
            return render(request, 'quoteapp/author.html', {'form': form})

    return render(request, 'quoteapp/author.html', {'form': AuthorForm()})


@login_required
def quote(request):
    tags = Tag.objects.all()
    authors = Author.objects.all()

    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            new_quote = form.save(commit=False)  # Зберігаємо форму без збереження в базу даних
            new_quote.autor = Author.objects.get(fullname=request.POST['author'])
            new_quote.save()
            choice_tags = Tag.objects.filter(name__in=request.POST.getlist('tags'))
            for tag in choice_tags.iterator():
                new_quote.tags.add(tag)

            return redirect(to='quoteapp:main')
        else:
            return render(request, 'quoteapp/quote.html', {"tags": tags, 'author': authors, 'form': form})

    return render(request, 'quoteapp/quote.html', {"tags": tags, 'author': authors, 'form': QuoteForm()})


@login_required
def start_scraping(request):
    if request.method == 'POST':
        scraper.main()
    return render(request, 'quoteapp/scraper.html')


def about_author(request, author_id):
    author = get_object_or_404(Author, pk=author_id)
    return render(request, 'quoteapp/about.html', {'author': author})


def quotes_by_tag(request, tag_name):
    tag = get_object_or_404(Tag, name=tag_name)
    quotes = Quote.objects.filter(tags=tag)
    authors = Author.objects.all()
    tag_counts = Tag.objects.annotate(quote_count=Count('quote')).order_by('-quote_count')[:10]
    return render(request, 'quoteapp/quotes_by_tag.html', {"quotes": quotes, "tag": tag, 'author': authors, 'top_tags': tag_counts})

task_2/quotes/quoteapp/templates/quoteapp/about.html
{% extends "quoteapp/base.html" %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="author-details">
                <h3 class="author-title">{{author.fullname}}</h3>
                <p><strong>Born:</strong> <span class="author-born-date">{{author.born_date}}</span>
                    <span class="author-born-location"> in {{author.born_location}}</span></p>
                <p><strong>Description:</strong></p>
                <div class="author-description">
                    {{author.description}}
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

task_2/quotes/quoteapp/templates/quoteapp/author.html
{% extends "quoteapp/base.html" %}

{% block content %}

<form method="post" action="{%url 'quoteapp:author'%}">
    {% csrf_token %}
    <div class="mb-3">
        <label class="form-label">Enter full name: </label>
            {{form.fullname}}
        <span>{{ form.errors.fullname }}</span>
    </div>
    <div class="mb-3">
        <label class="form-label">Select born date: </label>
            {{form.born_date}}
        <span>{{ form.errors.born_date }}</span>
    </div>
    <div class="mb-3">
        <label class="form-label">Enter born location:</label>
            {{form.born_location}}
        <span>{{ form.errors.born_location }}</span>
    </div>
    <div class="mb-3">
        <label class="form-label">Add description: </label>
            {{form.description}}
        <span>{{ form.errors.description }}</span>
    </div>
    <div class="form-group mt-4 mb-1">
        <button type="submit" class="btn btn-success">Submit</button>
        <button type="reset" class="btn btn-success">Reset</button>
    </div>
</form>

{% endblock %}

task_2/quotes/quoteapp/templates/quoteapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> Main </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
<div class="container">

    <div class="container text-right">
        <div class="row align-items-start">
            <div class="col-8">
                <h1>
                    <a href="/" style="text-decoration: none">Quotes</a>
                </h1>
            </div>
            <div class="col-4">
                <ul class="nav justify-content-end">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="#">Hello!!! </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:register' %}">Create account</a>
                    </li>
                    {% endif %}
                </ul>

            </div>
        </div>
    </div>
    <div class="container text-right">

        <div class="col-12 ">
            <ul class="nav justify-content-end column-gap-3">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Add: </a>
                </li>
                <li class="nav-item">
                    <a class="btn btn-outline-success" href="/tag/" role="button">Tag</a>
                </li>
                <li class="nav-item">
                    <a class="btn btn-outline-success" href="/author/" role="button">Author</a>
                </li>
                <li class="nav-item">
                    <a class="btn btn-outline-success" href="/quote/" role="button">Quote</a>
                </li>

                <li class="nav-item">
                    <a class="btn btn-outline-success" href="/scraper/" role="button">Scrape quotes.toscrape.com</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>

    {% block content %} {% endblock %}
</div>
</body>
</html>

task_2/quotes/quoteapp/templates/quoteapp/index.html
{% extends "quoteapp/base.html" %}

{% block content %}


<div class="container">
    <div class="row">
        <div class="col-md-10">
            {% for quote in page_obj %}
            <div class="card border-primary mb-3">
                <div class="card-body">
                    <blockquote class="blockquote">
                        <p class="card-text"> {{ quote.quote }} </p>
                        <span> Author: <a href="{% url 'quoteapp:about_author' quote.author.id %}">{{ quote.author.fullname }}</a></span>
                    </blockquote>
                    <p class="card-text">Tags:
                        {% for tag in quote.tags.all %}
                        <a href="{% url 'quoteapp:quotes_by_tag' tag.name %}" class="badge bg-primary">{{ tag.name }}</a>
                        {% endfor %}
                    </p>
                </div>
            </div>
            {% endfor %}
            <nav aria-label="Page navigation example">
                <ul class="pagination">

        {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="?page=1">&laquo; first</a></li>
             <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">previous</a></li>
        {% endif %}

            <li class="page-item"><a class="page-link"> Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</a></li>

        {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">next</a></li>
            <li class="page-item"><a  class="page-link" href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a></li>
        {% endif %}
        </div>
        <div class="col-md-2">
            <div class="card border-primary mb-3">
                <div class="card">
                    <h2>Top Ten Tags</h2>
                    <ul>
                        {% for tag in top_tags %}
                        <a href="{% url 'quoteapp:quotes_by_tag' tag.name %}" class="badge bg-primary">{{ tag.name }}
                            ({{ tag.quote_count }})</a>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

task_2/quotes/quoteapp/templates/quoteapp/quote.html
{% extends "quoteapp/base.html" %}

{% block content %}

<form method="post" action="{%url 'quoteapp:quote'%}">
    {% csrf_token %}
    <div class="form-group">
        <label class="form-label">Enter quote:</label>
        <input type="text" class="form-control" name="quote" required>
        <span>{{ form.errors.quote }}</span>
    </div>
    <div class="form-group">
        <select name="author" class="form-select" required>
            {% for auth in author %}
            <option value="{{auth.fullname}}">{{auth.fullname}}</option>
            {% endfor %}
        </select>
    </div>

    <div class="form-group">
        <label> Select tags:
            <select class="form-select" name="tags" multiple="multiple" aria-label="Default select example" required>
                {% for tag in tags %}
                <option value="{{tag.name}}">{{tag.name}}</option>
                {% endfor %}
            </select>
        </label>
    </div>
    <div class="form-group mt-4 mb-1">
        <button type="submit" class="btn btn-primary">Submit</button>
        <button type="reset" class="btn btn-secondary">Reset</button>
    </div>
</form>

{% endblock %}

task_2/quotes/quoteapp/templates/quoteapp/quotes_by_tag.html
{% extends "quoteapp/base.html" %}

{% block content %}


<div class="container">
    <div class="row">
        <div class="col-md-10">
            {% for quote in quotes %}
            <div class="card border-primary mb-3">
                <div class="card-body">
                    <blockquote class="blockquote">
                        <p class="card-text"> {{ quote.quote }} </p>
                        <span> Author: <a href="{% url 'quoteapp:about_author' quote.author.id %}">{{ quote.author.fullname }}</a></span>
                    </blockquote>
                    <p class="card-text">Tags:
                        {% for tag in quote.tags.all %}
                        <a href="{% url 'quoteapp:quotes_by_tag' tag.name %}" class="badge bg-primary">{{ tag.name }}</a>
                        {% endfor %}
                    </p>
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="col-md-2">
            <div class="card border-primary mb-3">
                <div class="card">
                    <h2>Top Ten Tags</h2>
                    <ul>
                        {% for tag in top_tags %}
                        <a href="{% url 'quoteapp:quotes_by_tag' tag.name %}" class="badge bg-primary">{{ tag.name }} ({{ tag.quote_count }})</a>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

task_2/quotes/quoteapp/templates/quoteapp/scraper.html
{% extends "quoteapp/base.html" %}

{% block content %}

<h1>Click the button to start scraping</h1>
<form action="{% url 'quoteapp:start_scraping' %}" method="post">
    {% csrf_token %}
    <button type="submit">Start Scraping</button>
</form>
{% endblock %}

task_2/quotes/quoteapp/templates/quoteapp/tag.html
{% extends "quoteapp/base.html" %}

{% block content %}

<form method="post" action="{%url 'quoteapp:tag'%}">
    {% csrf_token %}
    <div class="form-group">
        <label>Enter the tag name:
            {{form.name}}
        </label>
        <span>{{ form.errors.name }}</span>
    </div>
    <div class="form-group mt-4 mb-1">
        <button type="submit" class="btn btn-success">Submit</button>
        <button type="reset" class="btn btn-success">Reset</button>
    </div>
</form>

{% endblock %}